/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/CommonComponents/LayoutWrapper";
import ReduxProvider from "@/redux/ReduxProvider";
import I18nProvider from "@/components/CommonComponents/I18nProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TacPlay Game Management Dashboard",
  description: "Generated by Rahul Mallik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <ReduxProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ReduxProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
